### ISSUE TITLE
[Feature?]: ConfirmDialog and Modal should share return props

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1131]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently the Modal and ConfirmDialog APIs are returning similar properties, but using separate Objects which has caused a clash in the naming (Modal is using 'buttonWrapper' which instead should be 'buttonGroup' to match Confirm Dialog).

The two APIs should return a shared props Object that will help keep the property naming consistent with all Dialogs throughout the lifespan of Pando.

### Examples 🌈

```typescript
function createConfirmDialogProps(options: ConfirmDialogOptions) {
  const dialogProps = createDialogProps()

  return {
    ...dialogProps,
    section: {
      ...dialogProps.section,
      role: 'alertdialog'
    }
  }
}
```

### Motivation 🔦

Headless-styles, ConfirmDialog, Modal, TS

**Comment by Rykus0** [comment]
If I remember, I did this because they are different.  Where the confirm dialog has a set of "confirm/cancel" buttons below the content, the modal has a single "close" icon button, which is up in the corner.  Maybe "closeButtonWrapper" to match Popover?  Or remove it entirely and handle it in the container styles, like Admonition? I definitely agree that we should be consistent.
