### ISSUE TITLE
[Feature?]: Use "neutral" sentiment in HS APIs

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1139]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

For all APIs that use the `default` sentiment, can be confusing when it also has another sentiment that acts as the functional "default option". One way to remedy this without shipping a major breaking change which contradicts our version standards, we can add a new sentiment called "neutral" which uses a conversion function that changes it to "default" under the hood.

Doing this will prevent additional CSS markup and should only include a few file changes (global types, helpers.tsx, and a few component files that need to `Exclude` the type option).

### Examples 🌈

```typescript
interface ButtonOptions {
  sentiment: 'default' | 'action' | 'neutral'
  ...
}

function createBtnClasses(sentiment) {
 ...
  return {
     sentimentClass: convertSentiment(sentiment) // returns current unless it is nuetral which converts to use default
  }
}

### Motivation 🔦

Headless-styles, Types, Helpers, RFC

**Comment by josh-degraw** [comment]
> For sure, so if we "linked" them 🤷‍♀️ , it would prevent massive breaking changes that change everything foundationally from the design files to the dev packages meaning:
> 
> Tokens still use the default category for neutral tokens (which is fine since the names would still be the same since it's the "default use case for a page" - layout related, not actions, etc.
> 
> Then, in the API's we just add a sentiment option called "neutral" which would just use the default tokens so no breaking changes. We just need to create a CSS class map that will convert:
> 
> .neutralBtn to instead use .defaultBtn as an example (linking? Mapping? IDK...).

> Or...just add those classes in the CSS files, but the conversion function seems better?

The only main problem I could see with just "linking" is that it could still be confusing if I do e.g.

```ts
const props = getButtonProps({ sentiment: 'neutral' })
```

and the class that comes back is `defaultBtn`. Specifically in terms of debugability and discoverability. 

I know it would _technically_ be a breaking change, but the library is technically still in preview and according to semver it's kinda technically anything goes at this point. Depending on how widely adopted the package is at this point, a breaking change may or may not have as much of an impact now as it would later, for example. But of course I don't have any data to know if it would be or not, obviously you guys should make the best decision you can with the information you have, not just on the whim of one guy haha.

If we're talking about moving to `neutral` in the long term, from a library design perspective I'd actually think to change the implementation class to `.neutralBtn` and map `default` to `neutral` instead of the other way around. That would still keep some backwards compatibility but still encourage the implementation and usage towards `neutral`, assuming that's the direction the library _is_ wanting to go in.
